### ISSUE TITLE
Drupal 7 support

### ISSUE THREAD

**Issue by Chi-teck** [hechoendrupal/DrupalAppConsole#275]
Hi there.
I just came across this project. It looks awesome. I really wish I knew about it before because I have started the same work.
Here it is: https://github.com/Chi-teck/drupal-code-generator

Do you have any plans for Drupal 7 support?

**Comment by dmouse** [comment]
Awesome more developers are interested in creating this kind of tool for Drupal!

As you can see https://github.com/hechoendrupal/DrupalAppConsole#project-goals at this point we are focused on creating commands for Drupal 8 in order to help developers to easily migrate to the new version.

Theres is actually a module that provide this type os functionality for D7 https://www.drupal.org/project/module_builder and as mentioned we really want to focues in the new Drupal release and we do not want to duplicate work.

Maybe in the future we include Drupal 7 support, If you want to we can ping you when this happen. 

We would be more than happy to have your help on this project. 

Feel free to open issues and send PR :)

**Comment by jmolivas** [comment]
Thanks for the kind words @Chi-teck :)

And as @dmouse said feel free to open an issue or send a PR

**Comment by Chi-teck** [comment]
I have had some look at the project. It seems you are developing something more generic than just code generator (new Drush like tool?). The generate commands are tied to Drupal 8 installation so it is not possible to support Drupal 7 without redesigning project architecture. I will proceed with Drupal 7 in *Drupal Code Generator* project and perhaps I will add some Drupal 8 generators there.

In any case feel free to grub any code from that project if needed.
Thanks for your work!
