### ISSUE TITLE
[RFC] - PSR code style?

### ISSUE THREAD

**Issue by egulias** [hechoendrupal/DrupalAppConsole#57]
Hi guys!
Amazing what you are doing.
Reading the code I've found myself reading "Drupal way" code style. I know Gardfield is in the PHP-FIG.
Why not changing to the PSR-1, PSR-2 code styles?
Would be much easier for us #symfony guys to read & contribute :smile:

**Comment by joshuataylor** [comment]
Yeah the generated code creates code like:
`class FoobarEntityAccessControlHandler extends EntityAccessControlHandler
{
`

This isn't a big deal, as PHPStorm can reformat directories to fit a certain code style, ie "Drupal style" one liners instead of PSR-2 (https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) style.
